districts = [
    {"name": "Bang Bon"},
    {"name": "Bang Kapi"},
    {"name": "Bang Khae"},
    {"name": "Bang Khen"},
    {"name": "Bang Kho Laem"},
    {"name": "Bang Khun Thian"},
    {"name": "Bang Na"},
    {"name": "Bang Phlat"},
    {"name": "Bang Rak"},
    {"name": "Bang Sue"},
    {"name": "Bangkok Noi"},
    {"name": "Bangkok Yai"},
    {"name": "Bueng Kum"},
    {"name": "Chom Thong"},
    {"name": "Din Daeng"},
    {"name": "Don Mueang"},
    {"name": "Dusit"},
    {"name": "Huai Khwang"},
    {"name": "Khan Na Yao"},
    {"name": "Khlong Sam Wa"},
    {"name": "Khlong San"},
    {"name": "Khlong Toei"},
    {"name": "Lak Si"},
    {"name": "Lat Krabang"},
    {"name": "Lat Phrao"},
    {"name": "Min Buri"},
    {"name": "Nong Chok"},
    {"name": "Nong Khaem"},
    {"name": "Pathum Wan"},
    {"name": "Phasi Charoen"},
    {"name": "Phaya Thai"},
    {"name": "Phra Khanong"},
    {"name": "Phra Nakhon"},
    {"name": "Pom Prap Sattru Phai"},
    {"name": "Prawet"},
    {"name": "Rat Burana"},
    {"name": "Ratchathewi"},
    {"name": "Sai Mai"},
    {"name": "Samphanthawong"},
    {"name": "Saphan Sung"},
    {"name": "Sathon"},
    {"name": "Suan Luang"},
    {"name": "Taling Chan"},
    {"name": "Thawi Watthana"},
    {"name": "Thon Buri"},
    {"name": "Thung Khru"},
    {"name": "Wang Thonglang"},
    {"name": "Watthana"},
    {"name": "Yan Nawa"},
    {"name": "พระนคร"},
    {"name": "ดุสิต"},
    {"name": "หนองจอก"},
    {"name": "บางรัก"},
    {"name": "บางเขน"},
    {"name": "บางกะปิ"},
    {"name": "ปทุมวัน"},
    {"name": "ป้อมปราบศัตรูพ่าย"},
    {"name": "พระโขนง"},
    {"name": "มีนบุรี"},
    {"name": "ลาดกระบัง"},
    {"name": "ยานนาวา"},
    {"name": "สัมพันธวงศ์"},
    {"name": "พญาไท"},
    {"name": "ธนบุรี"},
    {"name": "บางกอกใหญ่"},
    {"name": "ห้วยขวาง"},
    {"name": "คลองสาน"},
    {"name": "ตลิ่งชัน"},
    {"name": "บางกอกน้อย"},
    {"name": "บางขุนเทียน"},
    {"name": "ภาษีเจริญ"},
    {"name": "หนองแขม"},
    {"name": "ราษฎร์บูรณะ"},
    {"name": "บางพลัด"},
    {"name": "ดินแดง"},
    {"name": "บึงกุ่ม"},
    {"name": "สาทร"},
    {"name": "บางซื่อ"},
    {"name": "จตุจักร"},
    {"name": "บางคอแหลม"},
    {"name": "ประเวศ"},
    {"name": "คลองเตย"},
    {"name": "สวนหลวง"},
    {"name": "จอมทอง"},
    {"name": "ดอนเมือง"},
    {"name": "ราชเทวี"},
    {"name": "ลาดพร้าว"},
    {"name": "วัฒนา"},
    {"name": "บางแค"},
    {"name": "หลักสี่"},
    {"name": "สายไหม"},
    {"name": "คันนายาว"},
    {"name": "สะพานสูง"},
    {"name": "วังทองหลาง"},
    {"name": "คลองสามวา"},
    {"name": "บางนา"},
    {"name": "ทวีวัฒนา"},
    {"name": "ทุ่งครุ"},
    {"name": "บางบอน"}
]

district_map = {
    "บางบอน": "Bang Bon",
    "บางกะปิ": "Bang Kapi",
    "บางแค": "Bang Khae",
    "บางเขน": "Bang Khen",
    "บางคอแหลม": "Bang Kho Laem",
    "บางขุนเทียน": "Bang Khun Thian",
    "บางนา": "Bang Na",
    "บางพลัด": "Bang Phlat",
    "บางรัก": "Bang Rak",
    "บางซื่อ": "Bang Sue",
    "บางกอกน้อย": "Bangkok Noi",
    "บางกอกใหญ่": "Bangkok Yai",
    "บึงกุ่ม": "Bueng Kum",
    "จอมทอง": "Chom Thong",
    "ดินแดง": "Din Daeng",
    "ดอนเมือง": "Don Mueang",
    "ดุสิต": "Dusit",
    "ห้วยขวาง": "Huai Khwang",
    "คันนายาว": "Khan Na Yao",
    "คลองสามวา": "Khlong Sam Wa",
    "คลองสาน": "Khlong San",
    "คลองเตย": "Khlong Toei",
    "หลักสี่": "Lak Si",
    "ลาดกระบัง": "Lat Krabang",
    "ลาดพร้าว": "Lat Phrao",
    "มีนบุรี": "Min Buri",
    "หนองจอก": "Nong Chok",
    "หนองแขม": "Nong Khaem",
    "ปทุมวัน": "Pathum Wan",
    "ภาษีเจริญ": "Phasi Charoen",
    "พญาไท": "Phaya Thai",
    "พระโขนง": "Phra Khanong",
    "พระนคร": "Phra Nakhon",
    "ป้อมปราบศัตรูพ่าย": "Pom Prap Sattru Phai",
    "ประเวศ": "Prawet",
    "ราษฎร์บูรณะ": "Rat Burana",
    "ราชเทวี": "Ratchathewi",
    "สายไหม": "Sai Mai",
    "สัมพันธวงศ์": "Samphanthawong",
    "สะพานสูง": "Saphan Sung",
    "สาทร": "Sathon",
    "สวนหลวง": "Suan Luang",
    "ตลิ่งชัน": "Taling Chan",
    "ทวีวัฒนา": "Thawi Watthana",
    "ธนบุรี": "Thon Buri",
    "ทุ่งครุ": "Thung Khru",
    "วังทองหลาง": "Wang Thonglang",
    "วัฒนา": "Watthana",
    "ยานนาวา": "Yan Nawa",
    "จตุจักร":"Chatuchak"
}
